### ISSUE TITLE
Prey does not take Vulnerable into account

### ISSUE THREAD

**Issue by Vurttivertti** [Cartopol/STS_Community_Warlord_Mod#17]
I used Vuln Potion and then Prey on a enemy. The first hit did not do extra 50% damage like it should. Only the second hit took Vulnerable into account.

**Comment by Cartopol** [comment]
Solved in 0.0.4. Added a calculateCardDamage step before applying single target damage. Note: multiDamage on card description now uses static magicNumber value, so that it doesn't show misleading values when hovering over a vulnerable enemy.
