### ISSUE TITLE
Anticipation draws 5 cards while it should draw only 4

### ISSUE THREAD

**Issue by Vurttivertti** [Cartopol/STS_Community_Warlord_Mod#18]
Title says it all.

**Comment by Cartopol** [comment]
Do you mean that you choose 1 card to put into your hand and then draw 5 more cards? It should draw 4 more, but you will still end up with 5 cards in hand total. Or are you saying you should only be getting 4 cards total (1 seek + 3 draws)? 
Also note that if you have a draw pile of exactly 1 card, the Seek action will give it to you automatically, and then draw 4 more cards.
