### ISSUE TITLE
Finish Off + Fracture deals too much damage

### ISSUE THREAD

**Issue by Vurttivertti** [Cartopol/STS_Community_Warlord_Mod#6]
When you play Finish Off and then Fracture against blocking enemy who is Vulnerable, it deals too much damage. For me it seems that it counts the damage like this: 27 (34) * 2 * 2 * 1.5 * 1.5 = 243 (306). So for some reason it takes Vulnerable into account twice. If enemy is not blocking the amount of damage is correct. Or if you the enemy has no Vulnerable then the damage is correct too.

**Comment by Cartopol** [comment]
Solved in 0.0.4. Fracture no longer doubles its damage (which includes Vuln modifiers) but doubles its baseDamage.
